server:
  port: 10005

spring:
  application:
    name: message-service
  rabbitmq:
    host: 192.168.120.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10

# 日志级别
logging:
  level:
    com.qizhi: INFO

springdoc:
  api-docs:
    enabled: true
knife4j:
  enable: true
